# Generated by Django 3.2.9 on 2021-11-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título do Livro')),
                ('autor', models.CharField(max_length=250, verbose_name='Autor')),
                ('num_pages', models.IntegerField(verbose_name='Número de páginas')),
                ('description', models.CharField(max_length=250, verbose_name='Descrição')),
                ('year_launched', models.CharField(max_length=250, verbose_name='Ano de lançamento')),
            ],
        ),
    ]
