# Generated by Django 3.2.9 on 2021-11-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='autor',
            new_name='author',
        ),
    ]
